<?php
print"<!DOCTYPE html>";
print"<html lang="es-mx">";
print"<head>";
    print"<meta charset="UTF-8">";
    print"<meta http-equiv="X-UA-Compatible" content="IE=edge">";
    print"<meta name="viewport" content="width=device-width, initial-scale=1.0">";
    print"<title> MOUNTAIN DEW SODA </title>";
    print"<!--ENLACES A FONTS-->";
    print"<link rel="preconnect" href="https://fonts.googleapis.com">";
    print"<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>";
    print"<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400&display=swap" rel="stylesheet"> 
    print"<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>";
    print"<!--ENLACES A HOJAS DE ESTILO-->";
    print"<link rel="stylesheet" href="css/estilos.css">";
    print"<link rel="stylesheet" href="css/menu.css">";
    print"<link rel="stylesheet" href="css/pie.css">";
print"</head>";
print"<body>";
    print"<div class="menu-btn">";
        print"<i class="fas fa-bars"></i>";
    print"</div>";
    print"<div class="contenedor">";
        print"<header class="logo">";
          print"<h1>MOUNTAIN DEW </h1>";
        print"</header>";
       print"<nav class="nav-main">";
            print"<ul class="nav-menu">";
                print"<li>";
                    print"<a href="index.html">MENU</a>";
                print"</li>";
                print"<li>";
                    print"<a href="#">BUY ONLINE</a>";
               print"</li>";
                print"<li>";
                    print"<a href="#">SERVICE</a>";
                print"</li>";
                print"<li>";
                   print"<a href="#">SODAS</a>";
                print"</li>";
            print"</ul>";
            print"<ul class="nav-menu-right">";
                print"<li> ";
                    print"<a href="#">";
                        print"<i class="fas fa-search"></i>";
                    print"</a>";
                print"</li>";
            print"</ul>";
        print"</nav>";
        print"<img class="portada" src="images/mtn.jpg" alt="portada">";  
        print"<main class="mainClass">";
            print"<center>";
            print"<h1>Nuestra historia</h1>";
            print"<h2>Les damos la bienvenida.</h2>";
            print"<iframe width="560" height="315" src="https://www.youtube.com/embed/Nl7WKJWhRNw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>";
            print"<h2> THIS IS ONE AMERICAN SODA</h2>";
            <br><br>
           print"<div class="desarrollador">";
            print"<h3>Desarrollador web de este sitio:</h3>";
                print"<p>Nombre: ELIEZER SAID ROSAS CRUZ, ISRAEL ARTEAGA,DIEGO ARMANDO NAJERA, ESTUDIANTES DEL TECNOLOGICO DE ZACATEPEC ISC</p>";
                print"<img class="imgSelefie" src="images/mt.jpg" alt="selfie">";
            print"</div>";
           print"</center>";
       print" </main>";
        print"<aside class="lateralDerecha">";
            print"<center>";
            print"<h1>Avisos</h1>";
            print"<video controls class="videito">";
            print"<source src="media/mtndeww.mp4" type="video/mp4"/>";
                print"<p></p>";
            print"</video>";
            print"</center>";
        print"</aside>";
        print"<footer class="pie">";
           print"<div class="domicilio">";
                print"<h2> <br> Domicilio:</h2>";
               print" <address>";
                    print"<br> Av. CASA BLANCA #745 <br>";
      
                    print"<br>col. naucalpan<br>";
      
                    print"<br>CUIDAD DE MEXICO.<br>";
      
                    print"<br>ww.mounatindew.com<br>";
      
                    print"<br>559-373-1689 ext 1<br>";
      
                print"</address>";
           print" </div>";
            print"<div class="mapa">";
                print"<h2>Ubícanos en el mapa. <br> Da click</h2>";
                print"<img class="mapaIMG" src="images/mapaitz.png" alt="mapaitz">";
            print"</div>";
           print" <section class="social">";
                print"<p>Síguenos en</p>";
               print" <div class="links">";
                   print" <a href="#">";
                      print" <i class="fab fa-facebook-f"></i>";
                    print"</a>";
                    print"<a href="#">";
                    print"<i class="fab fa-twitter"></i>";
                    print"</a>";
                    print"<a href="#">";
                        print"<i class="fab fa-linkedin"></i>";
                    print"</a>";
                print"</div>";
            print"</section>";
        print"</footer>";  
   print" </div> "; 
print"</body>";
print"</html>";
?<php>
